/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Moklet
 */
public class TugasArray1 extends javax.swing.JFrame {
    String jns = "";
    int jml;
    /**
     * Creates new form TugasArray1
     */
    public TugasArray1() {
        initComponents();
        jns = null;
        panel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        pilih = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ket = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        hitung = new javax.swing.JButton();
        bil = new javax.swing.JComboBox<>();
        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        bil3 = new javax.swing.JTextField();
        bil4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("PROGRAM ARITMATIKA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 470, 30);

        pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH --", "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihActionPerformed(evt);
            }
        });
        getContentPane().add(pilih);
        pilih.setBounds(150, 80, 290, 30);

        jLabel3.setText("Jenis Aritmatika");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 80, 90, 30);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);
        jPanel1.add(ket);
        ket.setBounds(230, 150, 110, 30);

        panel.setBackground(new java.awt.Color(102, 102, 102));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Operasi"));
        panel.setLayout(null);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        panel.add(hitung);
        hitung.setBounds(170, 210, 110, 40);

        bil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        bil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilActionPerformed(evt);
            }
        });
        panel.add(bil);
        bil.setBounds(140, 40, 270, 30);
        panel.add(bil1);
        bil1.setBounds(140, 80, 270, 30);
        panel.add(bil2);
        bil2.setBounds(140, 110, 270, 30);
        panel.add(bil3);
        bil3.setBounds(140, 140, 270, 30);
        panel.add(bil4);
        bil4.setBounds(140, 170, 270, 30);

        jLabel4.setText("Jumlah Bilangan");
        panel.add(jLabel4);
        jLabel4.setBounds(20, 40, 110, 30);

        b1.setText("Bilangan 1");
        panel.add(b1);
        b1.setBounds(20, 80, 90, 30);

        b2.setText("Bilangan 2");
        panel.add(b2);
        b2.setBounds(20, 110, 90, 30);

        b3.setText("Bilangan 3");
        panel.add(b3);
        b3.setBounds(20, 140, 90, 30);

        b4.setText("Bilangan 4");
        panel.add(b4);
        b4.setBounds(20, 170, 90, 30);

        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        panel.add(hasil);
        hasil.setBounds(90, 280, 270, 90);

        jPanel1.add(panel);
        panel.setBounds(20, 140, 430, 390);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 570);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(170, 120, 210, 30);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 140, 430, 370);

        setBounds(0, 0, 499, 613);
    }// </editor-fold>//GEN-END:initComponents

    private void pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihActionPerformed
        setJenis();
    }//GEN-LAST:event_pilihActionPerformed

    private void bilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }//GEN-LAST:event_bilActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
         Double hsl = 0.0;
         Double a1,a2,a3,a4;
         a1 = Double.parseDouble(bil1.getText());
         a2 = Double.parseDouble(bil2.getText());
         
         
         if(jns.equals("penjumlahan")){
             if(jml == 2) {
               hsl = a1+a2;
                 hasil.setText(""+ a1 + " + "+ a2 + " = "+ hsl);
             }
             if(jml == 3) {
                 a3 = Double.parseDouble(bil3.getText());
                 hsl = a1+a2+a3;
                 hasil.setText(" "+ a1 + " + "+ a2 + " + " + a3 + " = "+ hsl );
             }
             if(jml == 4) {
                 a4 = Double.parseDouble(bil4.getText());
                 a3 = Double.parseDouble(bil3.getText());
                 hsl = a1+a2+a3+a4;
                 hasil.setText(" "+ a1 + " + "+ a2 + " + " + a3 + " + " + a4 + " = " + hsl );
             }
         }
         
         if(jns.equals("pengurangan")){
             if(jml == 2) {
                 hsl = a1-a2;
                 hasil.setText(" "+ a1 + " - "+ a2 +" = "+ hsl );
             }
             if(jml == 3) {
                 a3 = Double.parseDouble(bil3.getText());
                 hsl = a1-a2-a3;
                 hasil.setText(" "+ a1 + " - "+ a2 + " - " + a3 + " = "+ hsl );
             }
             if(jml == 4) {
                 a3 = Double.parseDouble(bil3.getText());
                 a4 = Double.parseDouble(bil4.getText());
                 hsl = a1-a2-a3-a4;
                 hasil.setText(" "+ a1 + " - "+ a2 + " - " + a3 + " - " + a4 + " = " + hsl );
             }
         }
         if(jns.equals("perkalian")){
             if(jml == 2) {
                 hsl = a1*a2;
                 hasil.setText(" "+ a1 + " x "+ a2 +" = "+ hsl );
             }
             if(jml == 3) {
                 a3 = Double.parseDouble(bil3.getText());
                 hsl = a1*a2*a3;
                 hasil.setText(" "+ a1 + " x "+ a2 + " x " + a3 + " = "+ hsl );
             }
             if(jml == 4) {
                 a3 = Double.parseDouble(bil3.getText());
                 a4 = Double.parseDouble(bil4.getText());
                 hsl = a1*a2*a3*a4;
                 hasil.setText(" "+ a1 + " x "+ a2 + " x " + a3 + " x " + a4 + " = " + hsl );
             }
         }
         else if(jns.equals("pembagian")){
             if(jml == 2) {
                 hsl = a1/a2;
                 hasil.setText(" "+ a1 + " : "+ a2 +" = "+ hsl );
             }
             if(jml == 3) {
                 a3 = Double.parseDouble(bil3.getText());
                 hsl = a1/a2/a3;
                 hasil.setText(" "+ a1 + " : "+ a2 + " : " + a3 + " = "+ hsl );
             }
             if(jml == 4) {
                 a3 = Double.parseDouble(bil3.getText());
                 a4 = Double.parseDouble(bil4.getText());
                 hsl = a1/a2/a3/ a4;
                 hasil.setText(" "+ a1 + " : "+ a2 + " : " + a3 + " : " + a4 + " = " + hsl );
             }
         }
    
    }//GEN-LAST:event_hitungActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugasArray1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugasArray1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugasArray1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugasArray1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TugasArray1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JComboBox<String> bil;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JTextField bil3;
    private javax.swing.JTextField bil4;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> pilih;
    // End of variables declaration//GEN-END:variables

    public void setJenis() {
         if(pilih.getSelectedItem().equals("Penjumlahan")){
           jns = "penjumlahan";
           ket.setText("penjumlahan");
           panel.setVisible(true);
           bil.setEnabled(true);
    }
    else if(pilih.getSelectedItem().equals("Pengurangan")){
           jns = "pengurangan";
           ket.setText("pengurangan");
           panel.setVisible(true);
           bil.setEnabled(true);
    }
    else if(pilih.getSelectedItem().equals("Perkalian")){
           jns = "perkalian";
           ket.setText("perkalian");
           panel.setVisible(true);
           bil.setEnabled(true);
    }
    else if(pilih.getSelectedItem().equals("Pembagian")){
       jns = "pembagian";
           ket.setText("pembagian");
           panel.setVisible(true);
           bil.setEnabled(true);
    }
    else{
     
    }
    }

    public void getJumlah() {
        if(bil.getSelectedItem().equals("2")){
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            jml = 2;
        }
        if(bil.getSelectedItem().equals("3")){
            bil3.setVisible(true);
            bil4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
            jml = 3;
        }
        if(bil.getSelectedItem().equals("4")){
            bil3.setVisible(true);
            bil4.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            jml = 4;
        }
    }
}
